services:
  django:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        BUILD_ENVIRONMENT: local
    image: blog_backend_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "8000:8000"
    command: /start

  postgres:
    restart: always
    image: postgres:15
    container_name: blog_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./backend/.env.sample

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
