# Generated by Django 3.2.9 on 2021-11-14 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribedusers",
            name="conf_num",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
