# Generated by Django 3.2.9 on 2021-11-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_subscribedusers_conf_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribedUsers',
            new_name='SubscribedUser',
        ),
    ]
