# Generated by Django 3.2.9 on 2021-11-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_postnewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnewsletter',
            name='message',
            field=models.TextField(),
        ),
    ]
