# Generated by Django 3.2.9 on 2021-11-21 20:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20211109_1855"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="content"),
        ),
    ]
